# Generated by Django 5.2.4 on 2025-07-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlagDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='flag.flag')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='flag.flag')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('flag', 'depends_on'), name='unique_flag_dependencies')],
            },
        ),
    ]
