# Generated by Django 5.2.4 on 2025-07-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
