# Generated by Django 5.2.4 on 2025-07-08 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flag', '0002_alter_flag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('toggle_on', 'Toggle On'), ('toggle_off', 'Toggle Off'), ('auto_disable', 'Auto Disable')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flag.flag')),
            ],
        ),
    ]
