# Generated by Django 5.2.4 on 2025-07-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flag', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
